### ISSUE TITLE
Improve Numeric Stepper

### ISSUE THREAD

**Issue by TanyuS** [devex-web-frontend/dx-platform#101]
**For now.** 
Handler onValueChange in Numeric Stepper (NS) runs only 1) when buttons +/- click 2) input's onBlur

**The problem.** 
I've got an issue when my NS gets value and handler from props. The component has changable data every second (doesn't matter, but fast). So if I try to change the value in input manually and do not have enough time it (value) resets to the last one from props. It works with buttons +/- because its click runs onValueChange handler.

**Issue**
Run onValueChange handler during manual input value change

**Comment by Sky161** [comment]
#102

**Comment by raveclassic** [comment]
@Sky161 Can we close this?

**Comment by Sky161** [comment]
Yep
