### ISSUE TITLE
react-kit: Add possibility to override data states in RenderRemoteData

### ISSUE THREAD

**Issue by scink** [devex-web-frontend/dx-platform#130]
that will allow to define default data states for all project and override it in place if needed

**Comment by sutarmin** [comment]
@scink could you please share with us some examples of how this API extension will make DX better? I'm actually on your side about this idea, but just to be formal... :)

**Comment by scink** [comment]
i realized that `withDefaults` can be used instead of using `createRenderRemoteData`.
i close PR because it's redundant.
