### ISSUE TITLE
tools: Reexport storybook modules

### ISSUE THREAD

**Issue by sutarmin** [devex-web-frontend/dx-platform#133]
Recently we removed `utils/sotrybook.ts` and decided that we should use direct imports instead. But here is the thing: this package allows us not to have `@storybook/*` as a direct dependencies of our projects, just leaving `dx-tools storybook` as an interface to run storybook.

How correct is that in our projects to import stuff from `@storybook/*` packages when they are not listed in project dependencies? 
From this perspective, having `utils/storybook.ts` with reexports makes sense to me.

**Comment by raveclassic** [comment]
How does imports in separate module `utils/storybook.ts` differ from direct imports in components pages?

**Comment by sutarmin** [comment]
Let's say we have a project depending on `@devexperts/tools`. We build this project using `tools` and also use `dx-tools storybook` command from it, and that allows us not to have `@storybook/*` in that project dependencies because all of them are already included in `tools`. If you want to use direct imports to storybook in this situation, then you have to add `@storybook/*` dependencies directly to your project. And that requires us to manually keep storybook versions consistent (between direct deps and `tools` deps). But why to do that if we can reexport those deps from `tools` and this will:
1. Abstract us from storybook implementation
2. Make maintaining storybook versions upgrade much easier

**Comment by raveclassic** [comment]
Well I'm against any kind of API duplication. It's impossible to lock imports only on utils module and it doesn't make much sense to reexport the same already installed packages. So let's keep things clear and delegate version management to lockfiles/end-project/etc.

**Comment by sutarmin** [comment]
To me, it's more like abstraction than like duplication.

> reexport the same already installed packages

The thing is, end-project does not even need to have storybook-family packages in its deps. Everything is _already_ controlled by `tools` (`tools` installs its own version of storybook anyway).

The only reason why end-project needs to have `storybook/*` packages as a direct dependency _is those imports_. And even then, when we use `dx-tools storybook` command, it is building storybook using its own dependencies, no difference whether end-project does have storybook in dependencies or not. 

So with reexports we change _literally_ one thing. It is just whether we need or don't need to have direct dependencies of storybook for _mocking_ `storiesOf` and other helpers from storybook packages. That's it. Does is make sense for you?

**Comment by raveclassic** [comment]
Abstraction is good wetherr necessary and here I don't see a _good_ reason to introduce a wrapper around storybook. 

It does make sense but there's no straightforward way to force imports of `storiesOf` from `tools`. You end up with a mess of different imports in demo-page modules. _This_ is duplication and should be avoided.

If you arr concerned about inconsistency of different storybook versions, one from tools and one from end-project, then let's move the former to peer dependencies.

**Comment by raveclassic** [comment]
Furthermore I'd think about dropping tools at all. It's a useless layer of abstraction introduced fot the sake of abstraction. Newcomers should not only learn nuances of npm/yarn build/start steps, how to use storybook, how to configure CRA, but also this package. Is there any _good_ reason to force this abstraction with leaking details like storybook internald anyway?

/cc @mankdev

**Comment by sutarmin** [comment]
> there's no straightforward way to force imports

There is a way: if `@storybook/*` packages are not listed as direct dependencies, trying to import something from those packages is not allowed by linter. And the only reason they are installed now is those imports! :)

> I don't see a good reason to introduce a wrapper around storybook

I do, currently. The reasons are:
1. Webpack configs: another way we should copy them from project to project
2. Easier maintainability of build dependencies: upgrade one time in `tools` instead of upgrading in every other project.
3. A consistent approach with this abstraction across different projects makes moving developers from project to project easier.

> Newcomers should not only learn nuances of npm/yarn build/start steps, how to use storybook, how to configure CRA, but also this package

If this package will be well-maintained and documented, it is not much more than just "reusable webpack configs and build scripts" for newcomers. Moreover, they don't even need how it works, just how to use it, and then, if there is a need, learning is not __that__ difficult.

> Furthermore I'd think about dropping tools at all. 

It's a separate question. I will create an issue for discussing that. And while that topic is not discussed, I suggest stopping discussing this issue now and continuing if we decide not to drop `@devexperts/tools`.
