### ISSUE TITLE
Fix Selectbox component to be able to pass styles for menu elements and active menu element

### ISSUE THREAD

**Issue by sutarmin** [devex-web-frontend/dx-platform#20]
1) Now we have `container__item_isActive` in `props.theme` but it isn't used inside component at all. We need to make use of it.
2) Now if you pass `props.theme.container__item` value, it will reset default active value and active menu item won't be highlighted. This bug should also be fixed

**Comment by sutarmin** [comment]
Now Selectbox already has both of API's, so it is already bloated. If we want to avoid bloating then I suggest removing theme from props at all. Now it looks like this:
```
theme: {
		container_isOpened?: string;
		container__popover?: string;
		container__popover__content?: string;
		container__menu?: string;
		container__menu_hasSelectedItem?: string;
		container__item?: string;
		container__item_isActive?: string;
		container__item__text?: string;
		container__item__activeIcon?: string;
		container__anchor?: string;
		container__anchor__content?: string;
		container__anchor__text?: string;
		container__anchor__content_hasCaret?: string;
		container__anchor__wrapperCaret?: string;
		container__anchor__caret?: string;
		container__anchor__caret_isReversed?: string;
	};
```
This theme properties used only for passing them to Anchor, Menu and Popover (incluiding `container_isOpened`). If we remove `theme`, we'll have just one API (passing custom elements) as you want. What do you think about it?

**Comment by dramoturg** [comment]
Maybe use subtheme intead flat list.

**Comment by raveclassic** [comment]
@sutarmin this requires additional refactoring without any profit (currently). That's why I'd prefered this issue to be closed because such refactoring is out of scope and original problem is solved.
