### ISSUE TITLE
Make clear, Increment and decrement icons optional in SteppableInput

### ISSUE THREAD

**Issue by zeihlis** [devex-web-frontend/dx-platform#30]
Sometimes we don't need any icons in SteppableInput and thus have to use empty html tags to prevent typescript errors.

**Comment by raveclassic** [comment]
Seems like SteppableInput was incorrectly ported from dx-components, these icons are optional there https://github.com/devex-web-frontend/dx-components/blob/master/src/components/SteppableInput/SteppableInput.tsx#L46
