### ISSUE TITLE
Update tsconfig.json in react-kit

### ISSUE THREAD

**Issue by raveclassic** [devex-web-frontend/dx-platform#5]
- add `noUnusedLocals`
- remove `suppressImplicitAnyIndexErrors`
  
mirrors https://github.com/devex-web-frontend/dx-components/issues/49

**Comment by sutarmin** [comment]
I suppose this is not actual, tsconfig satisfies these requirements already: https://github.com/devex-web-frontend/dx-platform/blob/master/packages/react-kit/tsconfig.json#L4
